<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2GVCL39" ignored="6" name="Regression" tests="31" failures="10" timestamp="2022-05-04T09:25:44 IST" time="17.839" errors="0">
  <testcase name="A" time="0.007" classname="annotations.AnnotationsTestNG"/>
  <testcase name="A" time="0.023" classname="assertion.AssertionClass">
    <failure type="java.lang.AssertionError" message="did not expect [450] but found [450]">
      <![CDATA[java.lang.AssertionError: did not expect [450] but found [450]
at assertion.AssertionClass.A(AssertionClass.java:34)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="B" time="0.007" classname="annotations.AnnotationsTestNG"/>
  <testcase name="verifyUserCanUploadFile" time="0.002" classname="annotations.AnnotationsTestNG"/>
  <testcase name="A" time="0.023" classname="enable.EnabledInTestNG">
    <failure type="java.lang.AssertionError" message="did not expect [450] but found [450]">
      <![CDATA[java.lang.AssertionError: did not expect [450] but found [450]
at enable.EnabledInTestNG.A(EnabledInTestNG.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="B" time="0.004" classname="assertion.AssertionClass">
    <failure type="java.lang.AssertionError" message="User is displayed after deletion expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
at assertion.AssertionClass.B(AssertionClass.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase name="verifyUserCanUploadFile" time="0.005" classname="assertion.AssertionClass">
    <failure type="java.lang.AssertionError" message="Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@79360a39]">
      <![CDATA[java.lang.AssertionError: Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@79360a39]
at assertion.AssertionClass.verifyUserCanUploadFile(AssertionClass.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanUploadFile -->
  <testcase name="A" time="0.067" classname="assertion.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [4500] but found [450],
	did not expect [450] but found [450]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [4500] but found [450],
did not expect [450] but found [450]
at assertion.SoftAssertionClass.A(SoftAssertionClass.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="B" time="0.013" classname="enable.EnabledInTestNG">
    <failure type="java.lang.AssertionError" message="User is displayed after deletion expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
at enable.EnabledInTestNG.B(EnabledInTestNG.java:15)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase name="B" time="0.008" classname="assertion.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User is displayed after deletion expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is displayed after deletion expected [false] but found [true]
at assertion.SoftAssertionClass.B(SoftAssertionClass.java:24)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase name="verifyUserCanUploadFile" time="0.007" classname="assertion.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@28467807]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@28467807]
at assertion.SoftAssertionClass.verifyUserCanUploadFile(SoftAssertionClass.java:53)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanUploadFile -->
  <testcase name="addNewUserInSystem" time="0.06" classname="dataprovider.DataProviderInTestNG"/>
  <testcase name="addNewUserInSystem" time="0.009" classname="dataprovider.DataProviderInTestNG"/>
  <testcase name="sampleTestCase" time="0.004" classname="invocation.InvocationInTestNG"/>
  <testcase name="sampleTestCase" time="0.001" classname="invocation.InvocationInTestNG"/>
  <testcase name="zTestCase" time="0.098" classname="assertion.AssertionClass"/>
  <testcase name="sampleTestCase" time="0.002" classname="invocation.InvocationInTestNG">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at invocation.InvocationInTestNG.sampleTestCase(InvocationInTestNG.java:16)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sampleTestCase -->
  <testcase name="sampleTestCase" time="0.014" classname="invocation.InvocationInTestNG"/>
  <testcase name="sampleTestCase" time="0.009" classname="invocation.InvocationInTestNG"/>
  <testcase name="verifyUserCanBeAdded" time="0.004" classname="dependent.DependentTestCasesInTestNG"/>
  <testcase name="zTestCase" time="0.017" classname="assertion.SoftAssertionClass"/>
  <testcase name="verifyUserCanLoginWithValiedCredentials" time="0.009" classname="annotations.SampleAnnotationTestNG"/>
  <testcase name="verifyUserCanNotLoginWithInValiedCredentials" time="0.008" classname="annotations.SampleAnnotationTestNG"/>
  <testcase name="verifyUserCanBeEdited" time="0.011" classname="dependent.DependentTestCasesInTestNG">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependent.DependentTestCasesInTestNG.verifyUserCanBeEdited(DependentTestCasesInTestNG.java:19)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanBeEdited -->
  <testcase name="A" time="0.003" classname="priority.PriorityInTestNG"/>
  <testcase name="verifyUserCanUploadFile" time="0.009" classname="priority.PriorityInTestNG"/>
  <testcase name="B" time="0.009" classname="priority.PriorityInTestNG"/>
  <testcase name="verifyUserCanBeDeleted" time="0.0" classname="dependent.DependentTestCasesInTestNG">
    <skipped/>
  </testcase> <!-- verifyUserCanBeDeleted -->
  <testcase name="verifyURLIsBrockenOrNot" time="2.089" classname="brockenlink.BrockenLinkClass"/>
  <testcase name="addNewUserInSystem" time="2.709" classname="dataprovider.DataProviderInTestNG2"/>
  <testcase name="addNewUserInSystem" time="3.296" classname="dataprovider.DataProviderInTestNG2"/>
  <testcase name="@AfterSuite afterSuiteAnnotation" time="0.0" classname="annotations.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuiteAnnotation -->
  <testcase name="@BeforeSuite beforeSuiteAnnotation" time="0.0" classname="annotations.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuiteAnnotation -->
  <testcase name="@AfterTest afterTestAnnotation" time="0.0" classname="annotations.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest afterTestAnnotation -->
  <testcase name="verifyUserCaqnBeaddedWithUserName" time="0.0" classname="dataprovider.DataProviderInTestNG">
    <ignored/>
  </testcase> <!-- verifyUserCaqnBeaddedWithUserName -->
  <testcase name="@BeforeTest beforeTestAnnotation" time="0.0" classname="annotations.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTestAnnotation -->
  <testcase name="zTestCase" time="0.0" classname="enable.EnabledInTestNG">
    <ignored/>
  </testcase> <!-- zTestCase -->
</testsuite> <!-- Regression -->
